### PR TITLE
Using DevelopmentTools.locate if installed

### PR DESCRIPTION
**Pull request by luca-drf**
Addressing #18

### CODE REVIEW

**Comment by kaukas** [comment]
I am not sure what `DevelopmentTools` means but if we're using it why check the `.installed`? Can it be present but not installed? Is this check necessary?

**Comment by luca-drf** [comment]
`DevelopmentTools` is a class for invoking XCode Command Line Tools which are not a dependency for Homebrew. However after reading the definition of `DevelopmentTools#locate` I found that such check is not necessary so I removed it. :)

**Comment by kaukas** [comment]
Ok, I hope you know what it does. I am not sure what is the right way in either case.

Thank you for the contribution!

**Comment by luca-drf** [comment]
No problem :) I've tested it on MacOS 10.12. Apparently `MacOS#locate` is now deprecated and `DevelopmentTools#locate` must be used instead.

**Pull request closed without merging**
